In [4]:
import numpy as np

a1 = np.arange(8).reshape(2,4)
print(a1)
a2 = np.arange(8,16).reshape(2,4)
print(a2)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [6]:
a1+a2

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [7]:
#Senario 2: when both arrays have different shapes
a3 = np.arange(9).reshape(3,3)
a4 = np.arange(3).reshape(1,3)
print(a3,a4)

[[0 1 2]
 [3 4 5]
 [6 7 8]] [[0 1 2]]


In [8]:
a3+a4

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])